branches:
  only:
    - master
    - v1
os:
  - linux
  - osx
language: go
go:
  - 1.13.x
  - 1.14.x

before_install:
  - go get github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls -service=travis-ci