branches:
  only:
    - master
    - v1
os:
  - linux
  - osx
language: go
go:
  - 1.13.x
  - 1.14.x

script:
  - go test -coverprofile="coverage.txt" -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)